# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dleun/eece/lab8/lab8.srcs/sources_1/ip/dist_mem_gen_0instr_mem/dist_mem_gen_0instr_mem.xci
# IP: The module: 'dist_mem_gen_0instr_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dleun/eece/lab8/lab8.srcs/sources_1/ip/dist_mem_gen_0instr_mem/dist_mem_gen_0instr_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_0instr_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/dleun/eece/lab8/lab8.srcs/sources_1/ip/dist_mem_gen_0instr_mem/dist_mem_gen_0instr_mem.xci
# IP: The module: 'dist_mem_gen_0instr_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dleun/eece/lab8/lab8.srcs/sources_1/ip/dist_mem_gen_0instr_mem/dist_mem_gen_0instr_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_0instr_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
